# Generated by Django 3.2.18 on 2023-05-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_read_message_read_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read_by',
            new_name='read',
        ),
    ]
