# Generated by Django 3.2.18 on 2023-05-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_read_message_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.BooleanField(default=False),
        ),
    ]
